### ISSUE TITLE
Fix mechred arithmetic abort

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/Icepack#167]
see #163

**Comment by eclare108213** [comment]
Try uncommenting lines 563, 564 in icedrv_step.F90.  I never understood why we _didn't_ get errors with this commented out.  Then I forgot about it.

**Comment by apcraig** [comment]
As an aside, there are lots of these messages written to the log file.  Can we modify that or turn it off?

  (ridge_ice)Repeat ridging, niter =           1

The logic is in subroutine ridge_ice,

         if (iterate_ridging) then
            write(warnstr,*) subname, 'Repeat ridging, niter =', niter
            call icepack_warnings_add(warnstr)
         else
            exit rdg_iteration
         endif

**Comment by eclare108213** [comment]
Please do.  It shouldn’t be writing unless niter is bigger than 1.
e

**Comment by apcraig** [comment]
Just looking at the code, it must be iterating twice and writes that on the first iteration to log that it's going to a second iteration.  It does not write when it has converged.  Not sure if that is expected.  Do you want any of that information to the log file?  If so, what could be different?

**Comment by eclare108213** [comment]
Unless it's a problem for space or computing time on travis, let's leave the 'Repeat ridging' warning alone for now.  In my gx1 run, in only appears a few times.  We could change it so that it only writes if niter > 1; that rarely happens unless there's a serious problem and the code crashes.  The opening/closing data set is probably stressing the code a bit (which is good), and it's also not consistent with the other forcing.  We can change this behavior later if it becomes too annoying.  Or we can change it now if it's needed for travis.

**Comment by apcraig** [comment]
@eclare108213 I'm happy with that approach.
