### ISSUE TITLE
DOI info

### ISSUE THREAD

**Issue by duvivier** [CICE-Consortium/Icepack#188]
When we have a "general DOI" for the repo, we should add that information to the README.md as well as the documentation so that we can point users to that and ask them to please cite that when using this code.

**Comment by eclare108213** [comment]
Our general DOI number for the Icepack repo is 10.5281/zenodo.1213462.  
@duvivier knows this already, but for the record:
@apcraig created clearinghouse wiki pages for documentation etc. that can be kept up to date, so that pointers in older versions of the code (that gets cloned) do not break if we move things someplace else (as we have just done for the docs, to readthedocs).  E.g. see https://github.com/CICE-Consortium/CICE/wiki/Documentation-Index 
Details of the design are still under discussion.

**Comment by duvivier** [comment]
I have a response from Zenodo about creating the CICE-Consortium community and once this is done, it should be included in this documentation was well.

**Comment by eclare108213** [comment]
We also need to upload Icepack v1.0.0 to get a DOI number for it, and then associate it with our general Icepack repo DOI.

**Comment by eclare108213** [comment]
See
https://zenodo.org/communities/cice-consortium
and our Icepack v1.0.0 doi number:  10.5281/zenodo.1215746 
with upload at
https://zenodo.org/record/1215746#.Wsu99Y5RJGs
