### ISSUE TITLE
documenting/monitoring updates to forcing data

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/Icepack#209]
This issue is relevant for both Icepack and CICE.  The following is copied from PR #207:

We had outdated input datasets on conrad and gordon. @duvivier , I'm going to recommend that maybe we add a date string to the tar files on the ftp site indicating the date they were created. That way it's easier to tell if a "relatively newer" input data tar file might be on the ftp site. But that might also cause problems for travis, which is downloading the "current" file when it runs. Maybe we need both a generic and a date specific tar file or a link between them. I think as long as the tar files are cumulative (we don't delete data generally), we don't need to keep old tar files around, so this should not result in a large increase in data on ftp.

I have updated the input data on conrad and gordon and am running some tests, but suspect that should fix the problem. In a broader sense, we don't really have a way to tell whether the local input data is up to date for the current code on any particular machine nor how to communicate with the community that input data has been updated and relating the code versions and input data at any level. That's definitely a shortcoming. Maybe we can think about if/how we can do that. It's relatively low priority, but something to think about.

Maybe we can also implement a script that will quickly update the input data. Something that can be run quickly by any users, that downloads and untars the data into the local input data area. I'll see if I can put something like that together. In fact, we could then add a new option to create_newcase that would run that script. That could be quite handy.

**Comment by eclare108213** [comment]
Does ftp follow links?  If so, would this be sufficient:

- put a date string (yyyymmdd) on the file name
- link a generic filename to the latest version
- provide (up)date information on the forcing wiki page

A script to update the data could be handy if there are many steps to do, but right now I don’t think that’s true.  And for CICE, we won’t want to upload all of the data every time — the datasets are big.  Such a script might be handy for travis, though, and could be provided to users for their convenience.  I definitely wouldn’t put anything in the setup scripts that relies on an internet connection outside of the machine being worked on.  LANL HPC machines, for instance, can not ‘reach out’ to get/put anything unless there is a special portal opened specifically for it (e.g. github); most transfers have to be made from the outside in.

**Comment by duvivier** [comment]
I just got back from being out. I'm following up on this. I do not believe we've fixed the files so that they have date strings at this point, so I need to do that.

For some forcing files, we've just added _mmddyyyy to the file name (e.g. /Icepack_data/forcing/ISPOL_2004/ISPOL_atm_forcing_05092018.txt) but this is not consistently implemented for every file (e.g. /Icepack_data/forcing/CFS/cfsv2_2015_220_70_01hr.txt).

So, what date should I add and should I add it to each file? I don't necessarily know when the individual files were created, but I could add Oct. or Nov. dates since that's when I originally put the files together based on my information from the current tar files. Or I could use the current date. I know we don't want any file deleted (which is fine and understandable) but we may want to rename things like: Icepack_data/forcing/ISPOL_2004/ISPOL_atm_forcing.txt
to 
Icepack_data/forcing/ISPOL_2004/ISPOL_atm_forcing_11212017.txt (this is the file's creation date)
or 
Icepack_data/forcing/ISPOL_2004/ISPOL_atm_forcing_07042018.txt (current date)
and then not have any file named ISPOL_atm_forcing.txt since presumably that may be a name to which we would link. 

Thoughts? @apcraig @eclare108213 I want to hear from you. My preference is the file creation date, but I want to double check before I change everything in Icepack (and more importantly, CICE since there are more and larger files to deal with).

**Comment by apcraig** [comment]
@duvivier I would say do not change any current files.  What we have now is fine.  We should just starting adding date stamps to files moving forward.  What we want most is unique filenames and never a new file replacing an old one, it sort of doesn't matter the form of the filename.  It could be a date stamp or even an appended v01, v02, v03, or whatever.  Or even just a different name.  We don't need to go thru a process of renaming the files we currently have.

I think the issue at hand here is adding a date stamp to the tar files when they are updated.  We need that either as a copy or a link.  The issue mainly is that our tar files are generic names (which is needed for travis), but we provide no information when the input data tar file might be updated in the filename or on the web site.  Maybe we also need a document on the wiki that provides a log of changes in the input data tar files when they change including a date and what changed.  It would probably be good to keep track of that formally.

**Comment by duvivier** [comment]
Okay, I think I had only appreciated part of the issue. Here's a summary:

Problem:
- we have outdated input data on some machines
- no way to tell whether local input data is up to date for code
Solution:
- need to consistently add dates to input data files so we can better keep track of them
- add date string to tar files on ftp site to indicate when they’re created
- don’t keep old tar files around as long as tar files are cumulative
Concerns:
- how does this work with Travis CI?
- we don’t want users to have to download full tar files frequently. For CICE in particular this could get cumbersome.
- How do others do it? GFDL vs. NCAR/CESM

GFDL (MOM6) method: 
- document what to do on github wiki: https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#downloading-input-data
- If you are not using GFDL computers, you are responsible for downloading a tarball off the ftp (ftp://ftp.gfdl.noaa.gov/pub/aja/datasets/)
- tarballs are not consistently named with dates. Even with dates, some are yyyy.mm.dd vs. yyyymmdd

CESM method:
- CESM2.0 data available by GridFTP, Anonymous FTP, or Subversion (http://www.cesm.ucar.edu/models/cesm2/)
- During a case build the scripts check if the required input data files are in the local root directory. If not, the build aborts and missing files are listed. Then the user must get required data using the check_input_data script provided (http://esmci.github.io/cime/Tools_user/check_input_data.html).
- Data files are listed individually so that you don't get a huge tarball each time as data accumulates. No consistent naming, though some general move toward adding a yymmdd so that when you list them they appear in chronological order.

For the consortium:
- We could write into the $CASE.build type script the option to search for particular files name in the local inputdata directory. If it isn't there the build could stop and list the missing file. 
- However, at this point I think it would be the user's responsibility to go to the ftp, download the latest (only?) tarfile and get the missing data.
- I don't think we have the resources to maintain a check_input_data script and individual files the way NCAR does for CESM since we don't have a place to store all the files on Github or similar free of charge. This is why we went with a ftp here at NCAR.
- I don't think we should rename any of the input files currently, but we should start adding dates to them. Right now we don't add dates consistently (some already have mmddyyyy or no date string). I would propose the CESM version of yymmdd so that we can easily list files sequentially. 
- Make tar files cumulative so that we don't lose data. However, we should keep at max 2-3 available for general use so it gets less confusing. If possible, I agree that we could do an ftp link of the most recent tarball to something like Icepack_data_newest.tar.gz
- I suppose we could have individual files as well available through the ftp, but without the compression, etc. I foresee space issues. 

At this point I think we should discuss more at the telecon.

**Comment by eclare108213** [comment]
For date strings, I prefer yyyymmdd so that for something like 060209 I'm not (at first glance) wondering which pair is the year.

**Comment by duvivier** [comment]
Fine by me. I agree with that as well. :)

**Comment by duvivier** [comment]
I streamlined the procedure for adding new forcing files to the CICE ftp for both CICE and Icepack. I made the files available on the ftp in CICE_data_new.tar.gz, CICE_data_forcing_gx1_MONTHLY.tar.gz, and CICE_data_all.tar.gz. So if someone already has the data downloaded they could just download these new files. However, if a new user downloads data they will get everything they need.  

I've added documentation to the wiki about updated files as well as setting the stage for future additions. https://github.com/CICE-Consortium/CICE/wiki/CICE-Input-Data  or https://github.com/CICE-Consortium/Icepack/wiki/Icepack-Input-Data

The other major thing that has changed is that all the zipped tarballs now have a date string attached to them (e.g. CICE_data_all-20180920.tar.gz) on the CGD machines where the master tarballs are kept. In the ftp I have softlinked to the latest files and kept the original naming (e.g. CICE_data_all.tar.gz). This way I think that the testing scripts should not choke on the naming with dates, but we are able to keep track of which file is available and keep archives of the available files. I don't think we need to keep the archived tarballs forever, but we could decide how long we want to keep them (1 year, 5 years, whatever). 

The archives themselves are on the CGD machines. In case you need to find them, they're here:
/project/ppc/duvivier/CICE-Consortium_ftp_data/{CICE_all, Icepack_all}/
I have written scripts that nicely tar and zip the different subsets of data we provide. If, for whatever reason, I am not able to do it someone else with access to the CGD machines should be able to take it over easily.
