### ISSUE TITLE
Atmospheric boundary layer loop convergence on ustar.

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/Icepack#249]
We have added some code based on Mahrt and Sun, 1995, MWR to increase the wind speed in very stable boundary layer regimes. This has a namelist flag, use_coldair_outbreak_mod and only affects icepack_atmo.F90 (atmo_boundary_layer).

We also have code that will stop the iteration when ustar is changing less than a specified convergence tolerance. This could potentially reduce the number of iterations in icepack_atmo.F90 (atmo_boundary_layer). This can be turned off and the fixed value of iterations is used.

We also have some code to only print the diagnostic message about high frequency RASM coupling once.

**Comment by eclare108213** [comment]
Is the Mahrt and Sun option applied instead of the Jordan option that tries to address the same issue?  If so, then maybe the option should be generalized.  If not and it's applied on top, well, maybe we should rethink that.

**Comment by dabail10** [comment]
It is applied on top of the Jordan et al. option and only in regions where the temperature difference between the surface and the lower atmosphere is above a particular threshold.

**Comment by proteanplanet** [comment]
Please assign me to this issue.  I will be testing it in E3SM.

**Comment by proteanplanet** [comment]
Hi Dave,  Please can you point us to some documentation on this change.  Has it been written up in a paper as part of CESM V2?  This change will affect other coupled models, and it needs to be consistent with their boundary layers, too, so will most likely need to be implemented as a CESM option. As Elizabeth points out, it needs to be consistent with what is already in the boundary layer for CICE, hence the need for me to read up on the change. I've look at the paper, but I'm not seeing consistency with the existing CICE boundary layer method, probably due to a lack of intelligence on my part.  - Andrew

**Comment by proteanplanet** [comment]
I see that  use_coldair_outbreak_mod  switches on one line or not, but that doesn't necessarily make it consistent with the rest of the boundary layer parameterization.   Perhaps you are referring to a discussion with Elizabeth not on this issues page?

**Comment by dabail10** [comment]
I don't understand. We need it as a part of our CMIP runs. It is switchable and would be off in the default CICE model. So, no other groups have to use it. I am trying to keep our version up to date with the Consortium version.

**Comment by eclare108213** [comment]
Andrew and I talked about this offline, briefly.  We agree that it makes sense to incorporate it into our code base with an on/off flag, especially since CESM needs it.  The option will need to be documented along with a description of what the new physics is and how it interacts with the existing physics in the boundary layer parameterization.  That's the part that is not clear to Andrew and me.  If we find it questionable, then my recommendation is to include an explicit statement in the documentation that there is a question about the physical consistency, in hopes that someone out in the community (or one of us) will address that issue in a scientific study or at least explain it in the docs.  (That's how the Consortium is supposed to work, after all, and we have this kind of thing already, for the albedo.)

**Comment by dabail10** [comment]
I guess I was thinking that I had to demonstrate scientific results/publications with this modification before it was acceptable. I am certainly happy to add documentation. Not sure if and when anyone will ever do a paper on results with and without this.

**Comment by eclare108213** [comment]
See #315. 
If I understand correctly, the 'cold air outbreaks' code is not being implemented in cice v6, since CESM does not need it after all, and the only thing now being implemented is the reduction in iterations for the atmo boundary layer.  Just to clarify, is that what was referred to as "flux convergence"?   I admit that I didn't think of numerical convergence, but rather a physical convergence, e.g. deep ocean heat flux convergence.  I also don't think of ustar as a flux!  (m/s)  At the very least, please fix the title of the PR #315.  Thanks

**Comment by dabail10** [comment]
I agree that "flux convergence" is not quite right. Then main thing is to allow for reduced number of loop iterations for natmiter. The logic was implemented was to do nothing in the loop if ustar is converged. It doesn't explicitly exit the loop early.

**Comment by eclare108213** [comment]
Title suggestion for this PR:  atmo boundary layer loop convergence for ustar

**Comment by eclare108213** [comment]
Merged in both Icepack and CICE:
https://github.com/CICE-Consortium/Icepack/pull/315
https://github.com/CICE-Consortium/CICE/pull/452
