### ISSUE TITLE
subrountine of get ISPOL ocean forcing in icedrv_forcing.f90

### ISSUE THREAD

**Issue by cshengzhe** [CICE-Consortium/Icepack#340]
in the subroutine get_forcing(timestep) of icedrv_forcing.F90, when ocn_data_type = 'ISPOL',
call interp_coeff_monthly(recslot, c1intp, c2intp)

         sst_temp(:) = c1intp *  sst_data(mlast) + c2intp *  sst_data(mnext)
         sss     (:) = c1intp *  sss_data(mlast) + c2intp *  sss_data(mnext)
         uocn    (:) = c1intp * uocn_data(mlast) + c2intp * uocn_data(mnext)
         vocn    (:) = c1intp * vocn_data(mlast) + c2intp * vocn_data(mnext)
         qdp     (:) = c1intp *  qdp_data(mlast) + c2intp *  qdp_data(mnext)

why hmix does not show up here. I suppose hmix should be here too

**Comment by eclare108213** [comment]
My guess is that hmix did not appear here because it was deemed better to keep it fixed rather than use the values in the dataset.  Users are certainly allowed and encouraged to do their own tests, and if it turns out to be better to use the dataset value, then we can merge that code change into the repository.  The Consortium's implementation and configuration of applied forcing is only intended for testing the software.
