### ISSUE TITLE
User's guide

### ISSUE THREAD

**Issue by duvivier** [CICE-Consortium/Icepack#88]
Find and test instances of "CHECK" notation throughout the documentation (User's guide in particular) and verify we have the information we need for these sections.

**Comment by duvivier** [comment]
Elizabeth,
I'm searching through the documentation and trying to clean up instances of "CHECK" throughout the documentation. Can you check the following three sections (one instance each) and provide feedback about them?
3.6.4: https://cice-consortium.github.io/Icepack/user_guide/ug_troubleshooting.html --> It looks like part of the sentence about a write utility is missing. Do you know off hand where I should search for this?
4.1: https://cice-consortium.github.io/Icepack/developer_guide/dg_about.html ---> do the guiding principles look ok? 
4.3: https://cice-consortium.github.io/Icepack/developer_guide/dg_driver.html  --> the name looks appropriate. Did you want us to rename this driver file?

**Comment by eclare108213** [comment]
> 3.6.4: https://cice-consortium.github.io/Icepack/user_guide/ug_troubleshooting.html --> It looks like part of the sentence about a write utility is missing. Do you know off hand where I should search for this?

This hasn't been written yet.  What's there is a reminder to add information about the new utility that is now included in Icepack, which queries the parameter values and thus can be used to write them out for checking, when debugging.  There is a little documentation here 
https://cice-consortium.github.io/Icepack/developer_guide/dg_col_phys.html#the-warning-package
but we could use more in the troubleshooting section (how to query and then print info).

> 4.1: https://cice-consortium.github.io/Icepack/developer_guide/dg_about.html ---> do the guiding principles look ok?

Yes, I believe these are actually true.

> 4.3: https://cice-consortium.github.io/Icepack/developer_guide/dg_driver.html --> the name looks appropriate. Did you want us to rename this driver file?

I think we should rename that one as ice_restart_bgc.F90, since it only has bgc stuff in it now.  I'm still working on cleaning up the Icepack code, and this is something I was going to look at and maybe do.   I'll make an issue for it, so I don't forget.

**Comment by duvivier** [comment]
Fixed with PR #104
